- name: Callback to Jenkins
  hosts: all
  connection: local
  become: no
  tasks:
    - name: Printing variables for development
      ansible.builtin.debug:
        var: hostvars

    - name: Webhook Callback to Jenkins
      ansible.builtin.uri:
        url: "{{ jenkins_webhook_url }}"
        method: POST
        body_format: json
        validate_certs: no
        body:
          ansible_controller: {{ ansible_env.AWX_HOST }}
          ansible_workflow_id: {{ awx_workflow_job_id }}
      run_once: yes
